pull_request_rules:
  - name: merge automatically (when CI passes and PR is approved)
    conditions:
      - or:
          - "#approved-reviews-by >= 1"
          - author = dependabot[bot]
    actions:
      queue:
        method: rebase
