# SPDX-FileCopyrightText: 2023 Lin Yinfeng <lin.yinfeng@outlook.com>
# SPDX-FileCopyrightText: 2023 Unidealistic Raccoon <procyon@secureninja.maskmy.id>
#
# SPDX-License-Identifier: MIT

keys:
  - &pgp_procyon 2764AA78791D69DF7E8916D640802D0919B2FB7D
creation_rules:
  - pgp: *pgp_procyon
