# SPDX-FileCopyrightText: 2023 Unidealistic Raccoon <procyon@secureninja.maskmy.id>
#
# SPDX-License-Identifier: MIT

"$schema" = 'https://starship.rs/config-schema.json'

format = '$all'

right_format='$nix_shell'

[os]
disabled = false
format = 'on [$name](bold yellow) '

[time]
disabled = false
utc_time_offset = "-3"

[shell]
disabled = false
format = 'with [$indicator](bold yellow) '

[nix_shell]
format = '$state '
pure_msg = '[  pure \[$name\]](green)'
impure_msg = '[  impure \[$name\]](red)'
unknown_msg = '[  unknown \[$name\]](yellow)'
