# SPDX-FileCopyrightText: 2023 Unidealistic Raccoon <procyon@secureninja.maskmy.id>
#
# SPDX-License-Identifier: MIT

[[language]]
name = "nix"
auto-format = true

[language-server.nil]
config = { nil = { formatting = { command = ["nixpkgs-fmt"] } } }

[[language]]
name = "rust"

[language-server.rust-analyzer]
config = { check = { command = "clippy" } }
