tailnet: ENC[AES256_GCM,data:ILLYuYASknpmfXcTIiIE1SJLPLSbO1CKKU8=,iv:fY0ZWYR58c0dNJA+Gw1N6zZTJCpmX2HMGd3GqnvFcPU=,tag:/tr07IwqFURHB7dg+iSmkg==,type:str]
base_url: ENC[AES256_GCM,data:Vc7SpNDfLYcikTUbuOEFYjs1HLsW76H+ZQ==,iv:bzGphTJ8ZDKnrjANN5RLxVJU7+HPDWjkHGdsbbVRIPc=,tag:aZR0l1DKeKKPb2suACM4QA==,type:str]
oauth_client_id: ENC[AES256_GCM,data:HlxSJsHDl51EA7ES,iv:ZVyzymo2ifOP4tGk8VneQiheW77Jt85QhR7FM5140GQ=,tag:e6Jr9FSi0j0Yo64+v4rxCw==,type:str]
oauth_client_secret: ENC[AES256_GCM,data:HBLp95hdLtupp9bkJhQ8WIiu3rTWQPpb8HSZDPLsEWkDZezC/NSAYotV6ZJA14qeljwwtRYgbGaWzA==,iv:yrWSjij3gnO4e9RgIJnOhZt3UYDUkzam3+nPbCKAJdo=,tag:j9PKYl0tGulaD3OmOYNBXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1quvwy7893k74uqhkpgyn6zq9axlu2s3nhplg5ujzumh8fg4dfgzqs73xmq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRFgyeXh0SlNuZG90RUlt
            enJPRGZmbjdNdFAvNzRoVVFJamJnRm5tN21nCkErcklNMDJuUGRTVDlwYUhwRHE1
            bUM5UVg0c0hCNDNSMitxVGdJcC9oTVkKLS0tIFFjWHJNVnprM21LMS96TUMyWE9s
            c1RtbVdoTDVJazdKSjczWTdZQzVQTG8KTCfcnPv6tRlQnsgjs7Eya+VK4mMV8yiG
            e6iddH/2DPPHhqTwphQBgfHGKrNIA/XpbHP0xiKkPp7V7wjskO05sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T21:02:16Z"
    mac: ENC[AES256_GCM,data:FTRxGYSI3KGFAm6ug/gtJuiIh5cGkpXYQMjWY+m1Tqd0LyJzPOgfY7Ml9XD52uCII1CjXcJCpMzoL97XoGURjDQbslJRLMHMNjH9SDPFb3UNw8sljQse3k+KHLuqDUtAbaRHJMRkphR3+xioKlTA+6lORegP+zkWa2KBGc3aapo=,iv:/0+chwNRZHLpOsw7KvRm/gJdfwFVIlHAwex1wb5TK40=,tag:53ypZuue+ZbjHrgIg5Xs9w==,type:str]
    pgp:
        - created_at: "2023-11-24T20:58:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1qsfhX1ZRBOARAApXdJQAjohynF543c3E3+ScWmEPc6xHgZdVIEC/CZeggZ
            b9e2ZkjMJY/ZHvg6tfKIntaN62wwHOW2Kj08SrngivCQtBV19spjpkfNIL9ZZJCg
            7dJG8a4dZvqmdWAFwycscv2k544I8KQXPcozlLQEVlkXIUPJERvk1qfxTNsORPYg
            cS5G3gD3ktRXsuNcIJd/NeVm6ARO3/3o5t8/fZasmnkC/QnyudEGE2Kmetwf4nv3
            UOLRRTFiTzQiUM/r0I8w6pTcHE/fxH1JmBDDwHByMCV+kfxGJDL7JiS13Qoa5NC6
            P+AO5gLuyr9RWeC+bmCfkqStGKCgSfCJMKr3EGEo3xat4rGLKmJaSI6dw/7ir9vf
            +D/m/sFF82H+q7ioJVlW4NOfZGu5kTvbBgpybjhXcWqre5m9tPw6LP5ChuUcz5rd
            UuIKTh6uVbqzUOhsGqK7n43YVowj36+EL1gmYuIsswYLJQaka4+kZIzvqD9RXLzl
            GfaLj6aiFKA9VdnMODUhvVT2zqMv+Nb36r2TXEk8YJoS0kjDjulYXJwzLDRS9gNQ
            dyg4cFop6h+dGpwhYcey+vt0HSO1LxIDkgynuW6eOWGYeDheyh4G6OJEpYJ8RbjS
            zmoq60uQ/e9heN8CuAqcPVevGg8GqQrsRYiA4wehe71QE+zWWfUwZ9k6i63H+mbS
            XAGO0KNh6ZB0YsIpwy+ELGUhnJwheK/3gyVgC8lwXMwrI73YMsCkupCbuTfaEn1i
            5qh8JxyJorKcmPF3+TNhbGuzRjO15bUTtFspuFxsLohgOo2+l+Etx8To4npN
            =FRMM
            -----END PGP MESSAGE-----
          fp: 2764AA78791D69DF7E8916D640802D0919B2FB7D
    unencrypted_suffix: _unencrypted
    version: 3.8.1
