name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

env:
  flake: github:${{ github.repository }}/${{ github.sha }}
  nix-conf: |-
    max-jobs = auto
    accept-flake-config = true
    builders-use-substitutes = true
    substituters = https://nix-community.cachix.org https://procyon.cachix.org https://cache.garnix.io https://cache.nixos.org
    trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= procyon.cachix.org-1:VljSnjtMCpriTsvji4EotHS9UZJoPMOCVk//fmmvIto= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v2
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v8
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix flake check '${{ env.flake }}'
