name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

env:
  flake: github:${{ github.repository }}/${{ github.sha }}
  nix-conf: |-
    max-jobs = auto
    accept-flake-config = true
    allow-import-from-derivation = true

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v2
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix flake show '${{ env.flake }}'
      - run: nix flake check -L '${{ env.flake }}'
