name: "Publish"

on:
  push:
    branches:
      - "main"

jobs:
  flakehub:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@v7"
      - uses: "DeterminateSystems/flakehub-push@v3"
        with:
          rolling: true
          visibility: "public"
          name: "UnidealisticRaccoon/SnowyBurrow"
