name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */1 * * *"

jobs:
  get-flake-inputs:
    runs-on: ubuntu-latest
    outputs:
      flake-inputs: ${{ steps.get-flake-inputs.outputs.flake-inputs }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          sparse-checkout: flake.lock
      - id: get-flake-inputs
        run: |
          flake_inputs="$(jq -c '.nodes.root.inputs | {flake: keys}' flake.lock)"

          echo "flake-inputs=${flake_inputs}" >> "$GITHUB_OUTPUT"
  update-flake-inputs:
    name: update-${{ matrix.flake }}
    runs-on: ubuntu-latest
    needs: get-flake-inputs
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-flake-inputs.outputs.flake-inputs) }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: accept-flake-config = true
      - run: git config --global user.name "cyber-procyon[bot]"
      - run: git config --global user.email "150026596+cyber-procyon[bot]@users.noreply.github.com"
      - uses: cpcloud/flake-update-action@v2.0.1
        with:
          delete-branch: true
          dependency: ${{ matrix.flake }}
          pull-request-branch-prefix: update-
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-token: ${{ steps.generate-token.outputs.token }}
          pull-request-author: cyber-procyon[bot] <150026596+cyber-procyon[bot]@users.noreply.github.com>
